services:
  gen:
    entrypoint:
      - /home/python/venv/bin/python
      - /home/python/hymns/hymns.py
    image: ghcr.io/williamjacksn/hymns
    init: true
    volumes:
      - ./:/home/python/workdir
    working_dir: /home/python/workdir


  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/hymns
    init: true
    volumes:
      - ./:/home/python/hymns
    working_dir: /home/python/hymns
