name: Generate PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  gen-pdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: download-cache
          path: .local
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - run: pip install -r requirements.txt
      - run: python hymns.py
      - uses: actions/upload-artifact@v4
        with:
          name: hymns.pdf
          path: hymns.pdf
